kind: Secret
apiVersion: v1
metadata:
  name: vault-example
  annotations:
    avp.kubernetes.io/path: "argocd-v1/test/database"
    avp.kubernetes.io/kv-version: "1"
type: Opaque
data:
  username: <username>
  password: <password>
